### ISSUE TITLE
Reference Error 

### ISSUE THREAD

**Issue by shadowbq** [leighmcculloch/pdf-page-count#1]
You can't reference a file that does not exist in the actual gem. 

The gem.spec `spec = Gem::Specification::load('pdf-page-count.gemspec')` is not in the gem bundle.

```
 pdf-page-count --help
/home/username/.rvm/gems/ruby-2.1.2/gems/pdf-page-count-1.0.0/bin/pdf-page-count:15:in `block in <top (required)>': undefined method `version' for nil:NilClass (NoMethodError)
```

**Comment by leighmcculloch** [comment]
#2 merged fixes this and it's been pushed to rubygems in version 1.0.1.
