### ISSUE TITLE
swap out explict listings in gemspec

### ISSUE THREAD

**Issue by shadowbq** [leighmcculloch/pdf-page-count#3]
The new push in the `pdf-page-count/pdf-page-count.gemspec` 1.0.1 release did not include the ruby file 'version.rb' because of the explicit file listings:

swap out 

```
s.files       = [
    "lib/pdf-page-count.rb",
    "lib/pdf-page-count/file_util.rb",
    "lib/pdf-page-count/pdf_page_counter.rb",
    "lib/pdf-page-count/pdf_util.rb" ]
```

with 

```
s.files         = `git ls-files`.split($\)
```

**Comment by shadowbq** [comment]
remove the date line as well as it publishes bad dates.

```
s.date        = "2014-02-26"
```

Note: https://rubygems.org/gems/pdf-page-count show the 1.0.1 published a year ago.

**Comment by shadowbq** [comment]
consider swap the executables line to be more dynamic.

```
 s.executables = [ "pdf-page-count" ]
```

with 

```
 s.executables   = s.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
```

**Comment by leighmcculloch** [comment]
Thanks @shadowbq, this feedback is much appreciated! I believe this was the first gem I published, strangely I have other gems which already do some of these things but pdf-page-count was littered with some poor practices. Version 1.0.2 has these changes, locally on my system it looks like it installs and runs properly now, let me know if you see any other issues.
